name: CI

on:
  push:
    branches:
      - master
    tags:
      - "**"
  pull_request:

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    uses: bitcart/bitcart-actions/.github/workflows/lint.yml@master
    name: lint
    with:
      install-dependencies: |
        uv sync --frozen --compile-bytecode --no-dev --group web --group types --group lint --group test
      extra-checks: just ci-lint

  test:
    needs: lint
    name: test-${{ matrix.python-version }} (${{ matrix.group }}/${{ matrix.split-count }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        split-count: [4]
        group: [1, 2, 3, 4]

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: bitcart_test
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    env:
      TEST_ARGS: "-o junit_family=legacy --junitxml test-results/junit.xml --cov-report html:coverage"

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python ${{ matrix.python-version }}
        uses: bitcart/bitcart-actions/actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y libsecp256k1-dev

      - name: Install Python dependencies
        run: |
          uv sync --frozen --compile-bytecode --no-dev --group web --group otel --group test --group btc

      - uses: bitcart/bitcart-actions/actions/run-in-background@master
        name: Prepare daemon
        with:
          run: just testnet
          key: testnet

      - name: Run tests
        run: |
          ls -la test-results || true
          cat test-results/junit.xml || true
          just test -n 0 --splits ${{ matrix.split-count }} --group ${{ matrix.group }} --durations 0
          ls -la test-results || true
          cat test-results/junit.xml || true

      - name: Upload test results (before)
        uses: actions/upload-artifact@v6
        with:
          name: test-results-before${{ env.PYTHON }}-${{ matrix.group }}
          path: test-results/

      - uses: bitcart/bitcart-actions/actions/codecov@master
        name: Upload coverage to Codecov
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Tests - Python ${{ env.PYTHON }} - Group ${{ matrix.group }}
          flags: tests
          env_vars: PYTHON

      - uses: bitcart/bitcart-actions/actions/upload-test-results@master
        name: Upload test results
        with:
          suffix: py${{ env.PYTHON }}-${{ matrix.group }}

  functional-tests:
    uses: bitcart/bitcart-actions/.github/workflows/functional-tests.yml@master
    needs: test
    name: functional-tests
    with:
      install-dependencies: |
        uv sync --frozen --compile-bytecode --no-dev --group web --group otel --group test --group btc
      enable-redis: true
      enable-postgres: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  combine-coverage:
    uses: bitcart/bitcart-actions/.github/workflows/combine-coverage.yml@master
    needs: functional-tests
    name: combine-coverage
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
